source "https://rubygems.org"

group :test do
  gem "minitest"
  gem 'vcr', '~>2.0.0'
  gem 'webmock', '~>1.8.3'
  gem 'simplecov', :require => false
  gem 'turn', :require => false
end

gem "json"
gem "term-ansicolor"
gem "faraday"
gem "rake"
